MyCommunitySite/MyCommunitySite/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyCommunitySite.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Links()
        {
            return View();
        }

        public IActionResult FAQ()
        {
            return View();
        }
    }
}

MyCommunitySite/MyCommunitySite/Controllers/AppUserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using MyCommunitySite.Models;
using MyCommunitySite.Models.ViewModels;

namespace MyCommunitySite.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AppUserController : Controller
    {
        private UserManager<AppUser> userManager;
        private RoleManager<IdentityRole> roleManager;

        public AppUserController(UserManager<AppUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
        }

        public async Task<IActionResult> Index()
        {
            List<AppUser> users = new List<AppUser>();
            foreach (AppUser user in userManager.Users.ToList())
            {
                user.UserRoles = await userManager.GetRolesAsync(user);
                users.Add(user);
            }

            AppUserVM model = new AppUserVM
            {
                Users = users,
                Roles = roleManager.Roles
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            // get user for deletion
            AppUser user = await userManager.FindByIdAsync(id);
            if (user != null)
            {
                // delete user if found
                IdentityResult result = await userManager.DeleteAsync(user);
                // if delete fails show errors
                if (!result.Succeeded)
                {
                    string errorMessage = "";
                    foreach (IdentityError error in result.Errors)
                    {
                        errorMessage += error.Description +" | ";
                    }
                    TempData["message"]=errorMessage;
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> AddToAdmin(string id)
        {
            IdentityRole adminRole = await roleManager.FindByNameAsync("Admin");
            if (adminRole == null)
            {
                TempData["message"] = "Admin role does not exist. " + "Click 'Create Admin Role' button to create it.";
            }
            else
            {
                AppUser user = await userManager.FindByIdAsync(id);
                await userManager.AddToRoleAsync(user, adminRole.Name);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> RemoveFromAdmin(string id)
        {
            AppUser user = await userManager.FindByIdAsync(id);
            await userManager.RemoveFromRoleAsync(user, "Admin");
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteRole(string id)
        {
            IdentityRole role = await roleManager.FindByIdAsync(id);
            await roleManager.DeleteAsync(role);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> CreateAdminRole()
        {
            await roleManager.CreateAsync(new IdentityRole("Admin"));
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(RegisterVM model)
        {
            if (ModelState.IsValid)
            {
                var user = new AppUser { UserName = model.Username };
                var result = await userManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }
            return View(model);
        }
    }
}

MyCommunitySite/MyCommunitySite/Controllers/MessagesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using MyCommunitySite.Models;
using Microsoft.AspNetCore.Authorization;
using MyCommunitySite.Models.DomainModels;
using MyCommunitySite.Models.ViewModels;
using Microsoft.AspNetCore.Mvc.DataAnnotations;
using NuGet.Versioning;

namespace MyCommunitySite.Controllers
{
    public class MessagesController : Controller
    {
        readonly IMessageRepository messageRepo;
        readonly UserManager<AppUser> userManager;

        public MessagesController(IMessageRepository mRepo, UserManager<AppUser> uManager)
        {
            this.messageRepo = mRepo;
            this.userManager = uManager;
        }

        public async Task<IActionResult> Index()
        {
            // get message list
            List<Message> messages = await messageRepo.GetMessagesAsync();
            return View(messages);
        }

        [Authorize]
        public async Task <IActionResult> Message()
        {
            // pass in AppUsers for selecting Recipient
            ViewBag.AppUsers = await userManager?.Users.ToListAsync();
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Message(Message message)
        {
            // set sender & recipient
            if (ModelState.IsValid)
            {
                message.Sender = userManager?.GetUserAsync(User).Result;
                message.Recipient = userManager?.FindByIdAsync(message.RecipientId).Result;

                await messageRepo.AddMessageAsync(message);
                return RedirectToAction("Index");
            }

            return View(message);
        }

        public async Task<IActionResult> Filter(string sender, string date)
        {
            List<Message> messages = null;

            if (!string.IsNullOrEmpty(sender))
            {
                await Task.Run(() =>
                    messages =
                        (from m in messageRepo.Messages
                         where m.Sender.UserName == sender
                         select m).ToList());
            }
            if (!string.IsNullOrEmpty(date))
            {
                var searchDate = DateTime.Parse(date);
                await Task.Run(() =>
                    messages =
                        (from m in messageRepo.Messages
                         where m.TimeSent.Date == searchDate
                         select m).ToList());
            }
            return View("Index", messages);
        }

        [Authorize]
        public IActionResult DeleteMessage(int messageId)
        {
            messageRepo.DeleteMessage(messageId);

            var messages = messageRepo.Messages.ToList();
            return RedirectToAction("Index", messages);
        }

        [Authorize]
        public IActionResult DeleteReply(int messageId, int replyId)
        {
            messageRepo.DeleteReply(messageId, replyId);

            var messages = messageRepo.Messages.ToList();
            return RedirectToAction("Index", messages);
        }

        [Authorize]
        public IActionResult Reply(int messageId)
        {
            var replyVM = new ReplyVM { MessageId = messageId };
            return View(replyVM);
        }

        [HttpPost]
        public async Task<IActionResult> Reply(ReplyVM replyVM)
        {
            // get message that the reply is for
            var message = (from m in messageRepo.Messages.Include(m => m.Replies)
                           where m.MessageId == replyVM.MessageId
                           select m).First<Message>();

            // Reply is the domain model
            var reply = new Reply { ReplyText = replyVM.ReplyText };
            reply.Sender = userManager?.GetUserAsync(User).Result;
            reply.Recipient = message.Sender;

            if (ModelState.IsValid)
            {
                // store reply message w/reply in db
                message.Replies.Add(reply);
                await messageRepo.UpdateMessageAsync(message);

                return RedirectToAction("Index");
            }

            return View(replyVM);
        }
    }
}

MyCommunitySite/MyCommunitySite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Eugene Hikers</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyCommunitySite.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.1/css/all.css" integrity="sha-long-hash_code" crossorigin="anonymous">
</head>
@using Microsoft.AspNetCore.Identity
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Eugene Hikers</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="Index">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="History">History</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Messages" asp-action="Index">Messages</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav flex-grow-1 justify-content-end">
                        @if (User.Identity.IsAuthenticated)
                        {
                            // admins can access appuser page to make changes
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="AppUser" asp-action="Index">
                                        <span class="fas fa-cog"></span>&nbsp;Admin</a>
                                </li>
                            }
                            // signed-in user - log out & username
                            <li class="nav-item">
                                <form method="post" asp-action="LogOut" asp-controller="Account">
                                    <input type="submit" value="Log Out" class="btn btn-outline-dark" />
                                    <span class="text-dark">@User.Identity?.Name</span>
                                </form>
                            </li>
                        }
                        else {
                            // Get current action
                            var action = ViewContext.RouteData.Values["action"]?.ToString();
                            // anonymous user - register & login
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Register">
                                    <span class="fas fa-edit"></span>&nbsp;Register</a>
                            </li>
                            <li class="nav-item">
                                <a asp-action="LogIn" asp-controller="Account" class="btn btn-outline-dark">
                                    Log In</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-white">
        <div class="container">
            &copy; 2024 - Eugene Hikers
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>